services:
  db:
    image: postgres:17
    container_name: common-postgres-db
    ports:
      - "${POSTGRES_PORT:-54321}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
